name: Companio
options:
  bundleIdPrefix: com.companio
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    PRODUCT_BUNDLE_IDENTIFIER: com.companio.app
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    INFOPLIST_FILE: Companio/Info.plist

targets:
  Companio:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Companio
        excludes:
          - "Assets/Sounds/**"
    resources:
      - path: Companio/Assets
      - path: Companio/Resources
    info:
      path: Companio/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.companio.app
        INFOPLIST_FILE: Companio/Info.plist
        SWIFT_VERSION: "5.9"
    dependencies: []
